add various grammar and copy improvements
gemnasium/docs pull request #5
Opened 2016-10-11 19:52 UTC by jipiboily

2016-10-11 19:57 UTC, gravis requested changes

2016-10-11 19:57 UTC, gravis commented on docs/installation/docker_image.rst
> +To have access to the Gemnasium Enterprise image, you need to have a license from us, and we will then give you access to it via the Docker Hub. It is a private image.
Not really accurate: actually, we will authorize clients to access to our docker image, but they need to provide a  docker user for that. The licence sent will permit to run and sync with our servers.

2016-10-11 19:57 UTC, gravis commented on docs/installation/firewall.rst
> +Advisories can be created at any time on Gemnasium.com; that's why your instance synchronizes every five minutes.
I think this is not the case anymore, it's hourly now (I know it's not one of your change, but let's keep the doc clean :)

2016-10-11 19:58 UTC, jipiboily commented on docs/installation/docker_image.rst
> +To have access to the Gemnasium Enterprise image, you need to have a license from us, and we will then give you access to it via the Docker Hub. It is a private image.
That's what I meant, will rephrase.

2016-10-11 19:58 UTC, jipiboily commented on docs/installation/firewall.rst
> +Advisories can be created at any time on Gemnasium.com; that's why your instance synchronizes every five minutes.
You think...can you double check please? :)

2016-10-11 20:22 UTC, gravis commented on docs/installation/firewall.rst
> +Advisories can be created at any time on Gemnasium.com; that's why your instance synchronizes every five minutes.
`"@hourly"` in the code, confirmed :)

2016-10-12 16:35 UTC, jipiboily commented on docs/installation/docker_image.rst
> +To have access to the Gemnasium Enterprise image, you need to have a license from us, and we will then give you access to it via the Docker Hub. It is a private image.
> To have access to the Gemnasium Enterprise image, send us the Docker Hub user you want; we will share the image with that user.

?

2016-10-12 16:37 UTC, jipiboily commented on docs/installation/firewall.rst
> +Advisories can be created at any time on Gemnasium.com; that's why your instance synchronizes every five minutes.
Fixed.

2016-10-12 16:37 UTC, jipiboily commented on docs/installation/docker_image.rst
> +To have access to the Gemnasium Enterprise image, you need to have a license from us, and we will then give you access to it via the Docker Hub. It is a private image.
I pushed that version.

2016-10-12 17:06 UTC, merged